site_name: Code Snippets
site_url: https://example.com
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - content.tabs.link
    - content.code.anotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets 
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list         
# nav:
#   - Home: index.md
#   - About: about.md
#   - mkdocs: mkdocs.md
#   - Services:
#       - Connect: connect.md
#       - Docker: docker.md
#       - Git: git.md
#       - New Mac: new-mac.md
#       - VSCode: vscode.md
#   - AWS:
#       - TowerExecutionRole: AWSTowerExecutionRole/README.md
#       - TfScafold: tfscafold.md